name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TELEGRAM_TOKEN: <your-telegram-bot-token>
  OPENAI_API_KEY: <your-openai-api-key>

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t chatally .

      - name: Run tests
        run: docker run --rm chatally python -m unittest discover